/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sqltest2;

import java.sql.ResultSet;
import java.sql.Statement;
import java.text.*;
import java.util.Date;

/**
 *
 * @author AdMiN
 */
public class MenuFrame extends BasicVariable {
    ResultSet rs;
    /**
     * Creates new form MenuFrame
     */
    public MenuFrame() {
        initComponents();
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date date = new Date();
       // while(true){
        this.setTitle(dateFormat.format(date));
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MeatButton = new javax.swing.JButton();
        VetButton = new javax.swing.JButton();
        RiceButton = new javax.swing.JButton();
        ExtraButton = new javax.swing.JButton();
        FoodBtn1 = new javax.swing.JButton();
        FoodBtn2 = new javax.swing.JButton();
        FoodBtn3 = new javax.swing.JButton();
        FoodBtn4 = new javax.swing.JButton();
        FoodBtn5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MeatButton.setText("Meat");
        MeatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MeatButtonActionPerformed(evt);
            }
        });

        VetButton.setText("Vetgetable");
        VetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VetButtonActionPerformed(evt);
            }
        });

        RiceButton.setText("Rice");
        RiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RiceButtonActionPerformed(evt);
            }
        });

        ExtraButton.setText("Extra");
        ExtraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExtraButtonActionPerformed(evt);
            }
        });

        FoodBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FoodBtn2ActionPerformed(evt);
            }
        });

        FoodBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FoodBtn5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FoodBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FoodBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FoodBtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FoodBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MeatButton)
                        .addGap(34, 34, 34)
                        .addComponent(VetButton)
                        .addGap(22, 22, 22)
                        .addComponent(RiceButton)
                        .addGap(26, 26, 26)
                        .addComponent(ExtraButton))
                    .addComponent(FoodBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(421, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {FoodBtn1, FoodBtn2, FoodBtn3, FoodBtn4, FoodBtn5});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ExtraButton, MeatButton, RiceButton, VetButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MeatButton)
                    .addComponent(VetButton)
                    .addComponent(RiceButton)
                    .addComponent(ExtraButton))
                .addGap(32, 32, 32)
                .addComponent(FoodBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FoodBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FoodBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FoodBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(FoodBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {FoodBtn1, FoodBtn2, FoodBtn3});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MeatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MeatButtonActionPerformed
        FoodBtn1.setText(null);
        FoodBtn2.setText(null);
        FoodBtn3.setText(null);
        FoodBtn4.setText(null);
        FoodBtn5.setText(null);
        try { 
            Statement st = conn.createStatement();
            rs = st.executeQuery("SELECT MenuID,MenuName,Menucost FROM Menu WHERE Category ='Meat'");
            if (rs.next()) {
                FoodBtn1.setText(rs.getString("MenuName"));
            }
            if (rs.next()) {
                FoodBtn2.setText(rs.getString("MenuName"));
            }
            if (rs.next()) {
                FoodBtn3.setText(rs.getString("MenuName"));
            }
            if (rs.next()) {
                FoodBtn4.setText(rs.getString("MenuName"));
            }
            if (rs.next()) {
                FoodBtn5.setText(rs.getString("MenuName"));
            }
                    
            
        }
        catch(Exception e){    
        }
        

// TODO add your handling code here:
    }//GEN-LAST:event_MeatButtonActionPerformed

    private void FoodBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FoodBtn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FoodBtn5ActionPerformed

    private void VetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VetButtonActionPerformed
        FoodBtn1.setText(null);
        FoodBtn2.setText(null);
        FoodBtn3.setText(null);
        FoodBtn4.setText(null);
        FoodBtn5.setText(null);
        try { 
            Statement st = conn.createStatement();
            rs = st.executeQuery("SELECT MenuID,MenuName,Menucost FROM Menu WHERE Category ='Vet'");
            if (rs.next()) {
                FoodBtn1.setText(rs.getString("MenuName"));
            }
            if (rs.next()) {
                FoodBtn2.setText(rs.getString("MenuName"));
            }
            if (rs.next()) {
                FoodBtn3.setText(rs.getString("MenuName"));
            }
            if (rs.next()) {
                FoodBtn4.setText(rs.getString("MenuName"));
            }
            if (rs.next()) {
                FoodBtn5.setText(rs.getString("MenuName"));
            }
                    
            
        }
        catch(Exception e){    
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_VetButtonActionPerformed

    private void RiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RiceButtonActionPerformed
        FoodBtn1.setText(null);
        FoodBtn2.setText(null);
        FoodBtn3.setText(null);
        FoodBtn4.setText(null);
        FoodBtn5.setText(null);
        try { 
            Statement st = conn.createStatement();
            rs = st.executeQuery("SELECT MenuID,MenuName,Menucost FROM Menu WHERE Category ='Rice'");
            if (rs.next()) {
                FoodBtn1.setText(rs.getString("MenuName"));
            }
            if (rs.next()) {
                FoodBtn2.setText(rs.getString("MenuName"));
            }
            if (rs.next()) {
                FoodBtn3.setText(rs.getString("MenuName"));
            }
            if (rs.next()) {
                FoodBtn4.setText(rs.getString("MenuName"));
            }
            if (rs.next()) {
                FoodBtn5.setText(rs.getString("MenuName"));
            }
                    
            
        }
        catch(Exception e){    
        }        
// TODO add your handling code here:
    }//GEN-LAST:event_RiceButtonActionPerformed

    private void ExtraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExtraButtonActionPerformed
        FoodBtn1.setText(null);
        FoodBtn2.setText(null);
        FoodBtn3.setText(null);
        FoodBtn4.setText(null);
        FoodBtn5.setText(null);
        try { 
            Statement st = conn.createStatement();
            rs = st.executeQuery("SELECT MenuID,MenuName,Menucost FROM Menu WHERE Category ='Extra'");
            if (rs.next()) {
                FoodBtn1.setText(rs.getString("MenuName"));
            }
            if (rs.next()) {
                FoodBtn2.setText(rs.getString("MenuName"));
            }
            if (rs.next()) {
                FoodBtn3.setText(rs.getString("MenuName"));
            }
            if (rs.next()) {
                FoodBtn4.setText(rs.getString("MenuName"));
            }
            if (rs.next()) {
                FoodBtn5.setText(rs.getString("MenuName"));
            }
                    
            
        }
        catch(Exception e){    
        }
// TODO add your handling code here:
    }//GEN-LAST:event_ExtraButtonActionPerformed

    private void FoodBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FoodBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FoodBtn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExtraButton;
    private javax.swing.JButton FoodBtn1;
    private javax.swing.JButton FoodBtn2;
    private javax.swing.JButton FoodBtn3;
    private javax.swing.JButton FoodBtn4;
    private javax.swing.JButton FoodBtn5;
    private javax.swing.JButton MeatButton;
    private javax.swing.JButton RiceButton;
    private javax.swing.JButton VetButton;
    // End of variables declaration//GEN-END:variables
}
